config/routes.rb
SprayReport::Application.routes.draw do
  root :to => "pages#home"
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :posts do
    resources :comments
  end
  
  
  resources :sessions,      :only => [:new, :create, :destroy]
  resources :posts
  resources :relationships, :only => [:create, :destroy]
  
  get 'tags', to: 'tags#index', as: :tags
  
  get 'tag', to: 'tags#show', as: :tag
  
    
  get '/help',    to: 'pages#help'
  get '/about',   to: 'pages#about'
  get '/contact', to: 'pages#contact'
  
  get "/users/:id/:token", to: "users#verify_email", as: "verify_email"
  
  get '/signup',  to: 'users#new'
  get '/signin',  to: 'sessions#new'
  delete '/signout', to: 'sessions#destroy'
  

  

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div>
    <h2>
      <%= pluralize(object.errors.count, "error") %>
      prohibited this <%= object.class.to_s.underscore.humanize.downcase %>
      from being saved:
    </h2>
    <p>There were problems with the following fields:</p>
    <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
  
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol>
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
  <div class="feed-item">
  		<div class="user-summary">
				<div class="user-summary-links"><%= link_to gravatar_for(feed_item.user), feed_item.user %>
    			<%= link_to feed_item.user.name, feed_item.user %>
					<div class="story-edit">
					<% if current_user?(feed_item.user) %>
					 TODO edit
					<%= link_to "delete your story ", feed_item, method: :delete,
                                data: { confirm: "You sure?" },
                                title: feed_item.content %>
  															<% end %></div>
				</div>
  		</div>
		<div ><h2><%= feed_item.title %></h2></div>
		<div class="summary"><%= feed_item.content %></div>
		<span class="timestamp">Posted <%= time_ago_in_words(feed_item.created_at) %> ago.</span>
		</div>
</li>

app/views/shared/_page_header.html.erb
<% if signed_in? %>
<div class="row">
	<div class="span4 offset">
		<a href="<%= user_path(current_user) %>"><%= gravatar_for current_user, size: 52 %></a>
		<h1><%= current_user.name %></h1>
		<h4><%= pluralize(current_user.posts.count, "Story") %></h4>

		<% @user ||= current_user %>
	<div class="user-stats">
		<strong> 
			<a href="<%= following_user_path(@user) %>">
			<span id="following" class="stat"><%= @user.following.count %> following </a>

			<a href="<%= followers_user_path(@user) %>">
			<span id="followers" class="stat"><%= pluralize(@user.followers.count, "follower") %>
		</strong></a>
	</div>
</div>

	<div class="span3 offset4">
		<%= render 'shared/user_side_links' %>
	</div>
</div>
<% end %>

app/views/shared/_post_form.html.erb
<%= form_for(@post) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
			
		<p>
		  <%= f.text_field :title, placeholder: "Enter a title..." %>
		</p>
		<p>
    	<%= f.text_area :content, placeholder: "Compose new a new story..." %>
  	</p>
		<div class="field">
		  <%= f.text_field :tag_list, placeholder: "Tags (separated by commas)"%>
		</div>
	</div>
  <%= f.submit "Update your story", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <span id="following" class="stat">
      <%= @user.following.count %> following
    </strong>
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <span id="followers" class="stat">
      <%= pluralize(@user.followers.count, "follower") %>
    </strong>
  </a>
</div>

app/views/shared/_user_info.html.erb
<a href="<%= user_path(current_user) %>"><%= gravatar_for current_user, size: 52 %></a>
<h1><%= current_user.name %></h1>
<h4><%= pluralize(current_user.posts.count, "Story") %></h4>

app/views/shared/_user_side_links.html.erb
		<ul class="nav nav-list">
    	<li class="active"><%= link_to "Home", root_path, 
			class: "btn btn-large btn-block btn-primary icon-home icon-white" %></li>
    <li><%= link_to " Manage stories", current_user,
			class: "btn btn-large btn-block icon-book" %></li>
    <li><%= link_to " New Story", new_post_path, 
			class: " btn btn-large btn-block icon-pencil" %></li>
    </ul>

app/views/shared/_user_sidebar.html.erb
		<ul class="nav nav-list">
    	<li class="active"><%= link_to "Home", root_path, 
			class: "btn btn-large btn-block btn-primary icon-home icon-white" %></li>
    <li><%= link_to " Manage stories", edit_user_path(current_user),
			class: "btn btn-large btn-block icon-book" %></li>
    <li><%= link_to " New Story", new_post_path, 
			class: " btn btn-large btn-block icon-pencil" %></li>
    </ul>

app/views/shared/_visitor_sidebar.html.erb
<div class="span3 sidebar">
		<div class="row">
			<div class="span4 side-nav sign-up">
					<h1>Sign Up </h1>
					<%= link_to "Sign up now!", signup_path, :class => "btn btn-large btn-primary" %>
			</div>
		</div>
</div>