config/routes.rb
SprayReport::Application.routes.draw do
  root :to => "pages#home"
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :posts do
    resources :comments
  end
  
  
  resources :sessions,      :only => [:new, :create, :destroy]
  resources :posts
  resources :relationships, :only => [:create, :destroy]
  
  get 'tags', to: 'tags#index', as: :tags
  
  get 'tag', to: 'tags#show', as: :tag
  
    
  get '/help',    to: 'pages#help'
  get '/about',   to: 'pages#about'
  get '/contact', to: 'pages#contact'
  
  get "/users/:id/:token", to: "users#verify_email", as: "verify_email"
  
  get '/signup',  to: 'users#new'
  get '/signin',  to: 'sessions#new'
  delete '/signout', to: 'sessions#destroy'
  

  

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  #attr_accessible :name
  has_many :taggings
  has_many :posts, through: :taggings
  

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  
  # def show
  #   @tag = Tag.find_by_name(tag_params) || Tag.find_by_id(tag_params)
  # end
  # 
  
   def index
     @tags = Tag.all
   end
   
   def show
     @tag = Tag.find_by_name(params[:id]) || Tag.find_by_id(params[:id])
   end
  
  private
  
  def tag_params
     params.require(:tag).permit(:name, :tag_list)
   end
end

app/views/tags/index.html.erb
<h1>Tags</h1>
    <% @tags.each do |tag| %>
      <p><%= link_to tag.name.titleize, tag_path(tag) %></p>
    <% end %>

app/views/tags/show.html.erb
h1>Articles Tagged with <%= @tag.name %></h1>

<ul>
  <% @tag.posts.each do |post| %>
    <li><%= link_to post.title, post_path(post) %></li>
  <% end %>
</ul>