config/routes.rb
SprayReport::Application.routes.draw do
  root :to => "pages#home"
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :posts do
    resources :comments
  end
  
  
  resources :sessions,      :only => [:new, :create, :destroy]
  resources :posts
  resources :relationships, :only => [:create, :destroy]
  
  get 'tags', to: 'tags#index', as: :tags
  
  get 'tag', to: 'tags#show', as: :tag
  
    
  get '/help',    to: 'pages#help'
  get '/about',   to: 'pages#about'
  get '/contact', to: 'pages#contact'
  
  get "/users/:id/:token", to: "users#verify_email", as: "verify_email"
  
  get '/signup',  to: 'users#new'
  get '/signin',  to: 'sessions#new'
  delete '/signout', to: 'sessions#destroy'
  

  

end

app/models/post.rb
class Post < ActiveRecord::Base
  #attr_accessible :content
  belongs_to :user
  has_many :comments
  
  has_many :taggings
  has_many :tags, through: :taggings

  validates :user_id, presence: true
   validates :title, presence: true
  validates :content, presence: true

  default_scope order: 'posts.created_at DESC'

  def self.from_users_followed_by(user)
    followed_user_ids = "SELECT followed_id FROM relationships
                         WHERE follower_id = :user_id"
    where("user_id IN (#{followed_user_ids}) OR user_id = :user_id", 
          user_id: user.id)
  end

  def self.tagged_with(name)
    Tag.find_by_name!(name).posts
  end

  def self.tag_counts
    Tag.select("tags.*, count(taggings.tag_id) as count").
      joins(:taggings).group("taggings.tag_id")
  end

  def tag_list
    tags.map(&:name).join(", ")
  end

  def tag_list=(names)
    self.tags = names.split(",").map do |n|
      Tag.where(name: n.strip).first_or_create!
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate
  before_filter :authenticate_user, :only => [:index, :edit, :update, :destroy]
  
  
  def new
   @post = Post.new
   @title = "New story"
  end
  
  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comment.post_id = @post.id
  end
    
  
  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to root_url, :flash => { :success => "post created!" }
    else
      @feed_items = []
      render 'root_url'
    end
  end
  
  
  def edit
    @post = Post.find(params[:id])
    @title = "Edit Story"
  end

  def update
    if @post.update_attributes(post_params)
      redirect_to  edit_user_path(current_user), :flash => { :success => "Story updated." }
    else
      @title = "Update Story"
      render 'edit'
    end
  end
  
  def destroy
    @post.destroy
    redirect_to root_url, :flash => { :success => "Post deleted!"}
  end 

  private
    
    def authenticate_user
      @post = Post.find(params[:id])
      redirect_to root_url unless current_user?(@post.user)
    end
    
    private
    def post_params
      params.require(:post).permit(:title, :content, :tag_list)
    end
end

app/views/posts/_comment.html.erb
<div>
	<h6> Comment by <%= comment.author_name %></h6>
	<p class="comment"><%= comment.body %></p>
	<p>Posted <%= distance_of_time_in_words(comment.post.created_at, comment.created_at)%> later </p>
	
</div>

app/views/posts/_post.html.erb
<li>
  <span class="content"><%= post.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(post.created_at) %> ago.
  </span>
  <p>
	
	<% if current_user?(post.user) %>
 <%= link_to "Edit your story.", edit_post_path(post) %> or
		<%= link_to "Delete your story.", post, method: :delete,
                                data: { confirm: 'You sure?' },
                                title: post.content %>
  <% end %>
	</p>
</li>

app/views/posts/edit.html.erb
<% provide(:title, "Edit your story") %>

<!-- Main Area -->
<div class="main-area">
	<div class="container">
		<div class="row">
			<%= render 'shared/page_header' %>
			<h1>Write a new story</br><small></small></h1>
			<div class="span8">
				<%= form_for(@post) do |f| %>
					<%= render 'shared/error_messages', :object => f.object %>
					<p><%= f.text_field :title, placeholder: "Enter a title..." %></p>
					<p><%= f.text_area :content, placeholder: "Compose new a new story..." %></p>
					<p><%= f.text_field :tag_list, placeholder: "Tags (separated by commas)" %></p>
					<%= f.submit "Update your story", class: "btn btn-large btn-primary" %>
				<% end %>
			</div>
		</div>
	</div>
</div>
<!-- End Main Area -->

app/views/posts/new.html.erb
<% provide(:title, "New story") %>
<!-- Main Area -->
<div class="main-area">
	<div class="container">
		<div class="row">
			<%= render 'shared/page_header' %>
			<h1>Write a new story</br><small></small></h1>
			<div class="span8">
					<%= form_for(@post) do |f| %>
					<%= render 'shared/error_messages', :object => f.object %>
					<p><%= f.text_field :title, placeholder: "Enter a title..." %>	</p>
					<p><%= f.text_area :content, placeholder: "Compose new a new story..." %></p>
					<p><%= f.text_field :tag_list, placeholder: "Tags (separated by commas)" %></p>
					<%= f.submit "Save your story", class: "btn btn-large btn-primary" %>
				<% end %>
			</div>
		</div>
	</div>
</div>
<!-- End Main Area -->

app/views/posts/show.html.erb
<!-- End Main Area -->

</div>
<div class="main-area">
	<div class="container">
		<div class="row">
			<%= render 'shared/page_header' %>
			<div class="span8">
				<h1> <%= @post.title %> </h1>
				<p><%= @post.content %> </p>
				Tags: <%= raw @post.tags.map(&:name).map { |t| link_to t, tag_path(t) }.join(', ') %>
				<h3>Comments (<%= @post.comments.size %>)</h3>
				<%= render partial: 'posts/comment', collection: @post.comments %>
				<%= render partial: 'posts/comments/form' %>
				<p><%= link_to "<< Back to Stories List", posts_path %></p>
			</div>
		</div>
	</div>
</div>