config/routes.rb
SprayReport::Application.routes.draw do
  root :to => "pages#home"
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :posts do
    resources :comments
  end
  
  
  resources :sessions,      :only => [:new, :create, :destroy]
  resources :posts
  resources :relationships, :only => [:create, :destroy]
  
  get 'tags', to: 'tags#index', as: :tags
  
  get 'tag', to: 'tags#show', as: :tag
  
    
  get '/help',    to: 'pages#help'
  get '/about',   to: 'pages#about'
  get '/contact', to: 'pages#contact'
  
  get "/users/:id/:token", to: "users#verify_email", as: "verify_email"
  
  get '/signup',  to: 'users#new'
  get '/signin',  to: 'sessions#new'
  delete '/signout', to: 'sessions#destroy'
  

  

end

app/views/layouts/_footer.html.erb
<!-- Footer -->
<div class="footer-bar">
	<div class="container">
		
		<div class="row">
		
			<div class="span3">
			
				<p class="logo pull-left"<%= link_to "Spray Repost ", root_path, id: "logo" %></p>
				
				<li><%= link_to "Home", root_path %></li>
		    <li><%= link_to "Help", help_path %></li>
		    <% if signed_in? %>
		      <li><%= link_to "Users", users_path %></li>
		      <li id="fat-menu" class="dropdown">
		        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
		          Account <b class="caret"></b>
		        </a>
		        <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
		          <li><%= link_to "Profile", current_user %></li>
		          <li><%= link_to "Settings", edit_user_path(current_user) %></li>
		          <li class="divider"></li>
		          <li>
		            <%= link_to "Sign out", signout_path, method: "delete" %>
		          </li>
		        </ul>
		      </li>
		    <% else %>
		      <li><%= link_to "Sign in", signin_path %></li>
		    <% end %>
			</ul>
				
			</div>
			
			<div class="span3">
			
				<p class="logo">About<span>Us</span></p>
				
				<p>Suspendisse diam urna, pretium eu eleifend vel, convallis quis libero.</p>
				
				  <ul>
			      <li><%= link_to "About",   about_path %></li>
			      <li><%= link_to "Contact", contact_path %></li>
			      <li><a href="#">News</a></li>
			    </ul>
				
			</div>
	
		</div>
	</div>
<!-- End Footer -->
</div>

app/views/layouts/_header.html.erb
<div class="header-bar">
	<div class="container">

		<p class="logo pull-left"<%= link_to "Spray Repost ", root_path, id: "logo" %></p>
		
		<ul class="main-nav pull-right">
			<li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Help", help_path %></li>
      <% if signed_in? %>
        <li><%= link_to "Users", users_path %></li>
        <li id="fat-menu" class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            Account <b class="caret"></b>
          </a>
          <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
            <li><%= link_to "Profile", current_user %></li>
            <li><%= link_to "Settings", edit_user_path(current_user) %></li>
            <li class="divider"></li>
            <li>
              <%= link_to "Sign out", signout_path, method: "delete" %>
            </li>
          </ul>
        </li>
      <% else %>
        <li><%= link_to "Sign in", signin_path %></li>
      <% end %>
		</ul>
		
	</div>
<!-- End Header -->
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]--><!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_stylesheets.html.erb
<!--[if lt  IE 9]>
<script scr="html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen'%>
<%= stylesheet_link_tag 'blueprint/print', :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %> <![endif] -->
<%= stylesheet_link_tag 'custom', :media => 'screen'%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>

<link href="http://fonts.googleapis.com/css?family=Quicksand:300,400,700" rel="stylesheet" type="text/css">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>    
	<%= render 'layouts/header' %>
  <div class="container">	
    <section >
      <% flash.each do |key, value| %>
        <div class="flash <%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
    </section>
    <%= debug(params) if Rails.env.development? %>
  </div> 
	<%= render 'layouts/footer' %>
</body>
</html>